[10.x] Refactor the use of getScoutKeyName
laravel/scout pull request #509
Opened 2021-08-23 09:54 UTC by driesvints

This PR changes the use of getScoutKeyName. The most significant change is the removal of the use of the qualified column name in the `getScoutKeyName` method. Other changes are using the `getScoutKeyName` instead of `getKeyName` so people can modify what column is used to index search records.

The reason why the qualified column was removed was that if someone were to override `getScoutKeyName` (with the other changes in mind from this PR) the `toSearchableArray` wouldn't be compatible anymore as it won't append the correct column name and thus search records in Meilisearch won't index properly anymore. If we want to make `getScoutKeyName` adjustable for Meilisearch as well (as currently stated in the docs) then this change is necessary. As pointed out by @mmachatschek in https://github.com/laravel/scout/pull/484#issuecomment-863189618, Algolia doesn't suffer from this as it's using its own internal objectID mapping. 

The upgrade path for this unfortunately is that people will have to re-index their search records. If that's not wanted then we should re-consider removing the ability to override the key name. 

I'm also not entirely sure what the original reason for the use of the qualified column name was. I do not know if there will be a breaking change because if this.

I'd appreciate a review from you @mmachatschek before I mark this as ready to review for Taylor.

2021-08-23 10:23 UTC, mmachatschek requested changes
@driesvints 

please update the `\Laravel\Scout\Jobs\RemoveFromSearch::restoreCollection()` method and remove the "fix" to get the unqualified key name.

also update the `\Laravel\Scout\Tests\Fixtures\SearchableModelWithCustomKey::getScoutKeyName()` method.

2021-08-23 10:50 UTC, mmachatschek requested changes
@driesvints 

When changing `Searchable::getScoutKeyName()` the method `Searchable::queryScoutModelsByIds()` should be updated so that the key is uses a qualified column name? What do you think?

```diff
    public function queryScoutModelsByIds(Builder $builder, array $ids)
    {
        $query = static::usesSoftDelete()
            ? $this->withTrashed() : $this->newQuery();

        if ($builder->queryCallback) {
            call_user_func($builder->queryCallback, $query);
        }

        return $query->whereIn(
-            $this->getScoutKeyName(), $ids
+            $this->qualifyColumn($this->getScoutKeyName()), $ids
        );
    }
```

2021-08-23 12:31 UTC, driesvints commented
@mmachatschek did some of those changes.

> When changing Searchable::getScoutKeyName() the method Searchable::queryScoutModelsByIds() should be updated so that the key is uses a qualified column name? What do you think?

Should we also do this for the `makeAllSearchable`'s `orderBy` statement?

```diff
    public static function makeAllSearchable($chunk = null)
    {
        $self = new static;

        $softDelete = static::usesSoftDelete() && config('scout.soft_delete', false);

        $self->newQuery()
            ->when(true, function ($query) use ($self) {
                $self->makeAllSearchableUsing($query);
            })
            ->when($softDelete, function ($query) {
                $query->withTrashed();
            })
-            ->orderBy($self->getScoutKeyName())
+            ->orderBy($this->qualifyColumn($self->getScoutKeyName()))
            ->searchable($chunk);
    }
```

2021-08-23 13:07 UTC, mmachatschek requested changes
@driesvints Yes.

Both `Searchable::queryScoutModelsByIds()` and `Searchable::makeAllSearchable()` should have the qualifiedColumn call IMO.

Additionally after the changes with the `qualifiedColumn` name the Algolia driver should have the same behaviour as before the changes.

2021-08-23 13:07 UTC, mmachatschek commented on src/Searchable.php
> +            ->orderBy($self->getScoutKeyName())
```suggestion
            ->orderBy($self->qualifyColumn($self->getScoutKeyName()))
```

2021-08-23 13:39 UTC, driesvints commented
> Both Searchable::queryScoutModelsByIds() and Searchable::makeAllSearchable() should have the qualifiedColumn call IMO.

@mmachatschek done, can you check again?

> Additionally after the changes with the qualifiedColumn call the Algolia driver should have the same behaviour as before the changes.

How do we practically do this?

2021-08-23 13:42 UTC, mmachatschek approved these changes
> How do we practically do this?

Nothing to do here. Just wanted to point out that for algolia everything should be working as before now that you made the changes.

LGTM

2021-08-24 08:23 UTC, driesvints commented
Okay, this is ready for review now. I tried out the changes on both the Laravel.io and blade-ui-kit.com codebases without problems. @taylorotwell feel free to give this a review.

2021-08-24 08:59 UTC, mmachatschek commented
@driesvints MeiliSearch v0.21.0 was released yesterday. It brings breaking changes on the library level.
I'm not sure if there will be the 10.x release after merging this PR, but maybe lets wait for the update of the meilisearch/meilisearch-php library. The release of it should be out this week maybe even today.

2021-08-24 13:03 UTC, merged

2023-03-03 12:08 UTC, rosszt commented
Fantastic, this is a great improvement for me. I had this exact issue this week 👍