[10.x] Add Typesense engine
laravel/scout pull request #773
Opened 2023-10-17 14:19 UTC by jasonbosco

@taylorotwell @driesvints Following up from our conversation, this PR adds native support for [Typesense](https://github.com/typesense/typesense) (an open source alternative to Algolia) to Scout. 

It follows a code structure similar to the Algolia engine to maintain consistency.

CC: @karakhanyans @arayiksmbatyan

P.S. This PR supersedes #772.

2023-10-17 14:28 UTC, driesvints requested changes
Hi @jasonbosco, thanks for your PR. There's still quite a bit of styling improvements needed here. Can you make sure the code style of this PR adheres to the rest of the library? When done we can mark it as ready for Taylor to review. Thanks

2023-10-17 14:28 UTC, driesvints commented on config/scout.php
> +    'typesense' => [
```suggestion
    */

    'typesense' => [
```

2023-10-17 14:28 UTC, driesvints commented on config/scout.php
> +        'api_key'         => env('TYPESENSE_API_KEY', 'xyz'),
Please only use one space before `=>` assignments.

```suggestion
        'api_key' => env('TYPESENSE_API_KEY', 'xyz'),
```

2023-10-17 14:28 UTC, driesvints commented on src/EngineManager.php
> +     */
Please use FQN everywhere.

```suggestion
    /**
     * Create a Typesense engine instance.
     * 
     * @return \Laravel\Scout\Engines\TypesenseEngine
     *
     * @throws \Typesense\Exceptions\ConfigError
     */
```

2023-10-17 14:28 UTC, driesvints commented on src/Engines/TypesenseEngine.php
> + */
```suggestion
```

2023-10-17 14:28 UTC, driesvints commented on src/Engines/TypesenseEngine.php
> +     * @var Typesense
Please use FQN everywhere and add a one line comment like other docblocks.

2023-10-17 14:28 UTC, driesvints commented on src/Engines/TypesenseEngine.php
> +     * @var $searchOptions
```suggestion
     * @var array $searchOptions
```

2023-10-17 14:28 UTC, driesvints commented on src/Engines/TypesenseEngine.php
> +        if (!empty($this->searchOptions)) {
```suggestion
        if (! empty($this->searchOptions)) {
```

2023-10-17 14:28 UTC, driesvints commented on src/Engines/TypesenseEngine.php
> +        if (!empty($builder->orders)) {
```suggestion
        if (! empty($builder->orders)) {
```

2023-10-17 14:28 UTC, driesvints commented on src/Engines/TypesenseEngine.php
> +            $params['sort_by'] .= $this->parseOrderBy($builder->orders);
```suggestion

            $params['sort_by'] .= $this->parseOrderBy($builder->orders);
```

2023-10-17 14:28 UTC, driesvints commented on src/Engines/TypesenseEngine.php
> +     *
```suggestion
```

2023-10-17 15:56 UTC, jasonbosco commented
@driesvints Thank you for the quick review! 

@karakhanyans has fixed the linting issues and the `continuous-integration/styleci/pr` check now passes. Could you take a look now?

2023-10-18 12:44 UTC, driesvints commented
@jasonbosco a lot of the DocBlocks are still missing their first line comment. Could you add those?

2023-10-19 12:33 UTC, driesvints commented
Thanks all 👍

2023-10-26 21:21 UTC, taylorotwell commented
You're calling a few model methods I've never heard of:

`getCollectionSchema`
`typesenseQueryBy`

Can you explain both of these methods? What are they supposed to do? Examples? More detail in general please.

2023-10-27 15:15 UTC, jasonbosco commented
> `getCollectionSchema` 
> `typesenseQueryBy`
> 
> Can you explain both of these methods? What are they supposed to do? Examples? More detail in general please.

@taylorotwell In the current engine we have, these are methods that needed to be defined in the model. But @karakhanyans and I just discussed this, and we're going to take this opportunity to simplify this interface, and move it into the engine configuration, so these methods won't be required any more. Will share detailed docs once we make these changes.

2023-10-29 23:58 UTC, taylorotwell commented
Thanks

2023-11-10 17:29 UTC, jasonbosco commented
@taylorotwell We've updated the Typesense engine, and simplified the code to remove any dependencies on custom methods defined in the model. 

I've also updated the description of this PR with docs for the engine. 

Let me know what you think!

CC: @karakhanyans

2023-11-14 17:05 UTC, driesvints commented
@jasonbosco looks good. Will let @taylorotwell give the final review of this.

2023-11-28 21:23 UTC, taylorotwell commented
@jasonbosco I'm unable to get this working on a fresh Laravel application. I get the following error... have you tested in a real app?

![CleanShot 2023-11-28 at 15 22 54@2x](https://github.com/laravel/scout/assets/463230/f2d15f1a-d384-46be-8c94-e1169b5b9a7a)

2023-11-28 21:26 UTC, taylorotwell commented
Marking as draft. I tried to correct the error above which led to another error. Please test in fresh Laravel application then mark as ready for review.

2023-11-30 17:48 UTC, jasonbosco commented
@taylorotwell We've been looking into this. The root cause is that when we install [typesense-php](https://github.com/typesense/typesense-php) into a Laravel 10 application, it seems to pull in an older version of the package by default (4.0.1). But installing `typesense-php` in Laravel 8 and 9, pulls in the latest version of typesense-php (4.2) correctly. 

We suspect that there's some dependency in typesense-php which conflicts with a Laravel dependency. We're working on trying to identify this. I'll keep you posted.

2023-12-05 05:54 UTC, jasonbosco commented
@taylorotwell -

@karakhanyans has fixed the root cause of the issue in typesense-php. The latest code should now pull the correct version of typesense-php and fix the issue you saw.

2023-12-13 20:06 UTC, taylorotwell commented
@jasonbosco how do I handle soft deleted records? What do I add to my schema? Furthermore, if I'm using Typesense how can I delete all my collections for a fresh start?

2023-12-13 20:34 UTC, jasonbosco commented
@taylorotwell 

> how do I handle soft deleted records? What do I add to my schema?

Soft deletes are handled [here](https://github.com/laravel/scout/pull/773/files#diff-30cbc8fb802094edb92485725f009b63a895bcc546b84381b550883a17441129R59-R70). 

Essentially if `soft_delete` is set to `true` in the Scout config, then the engine syncs the [soft delete metadata](https://github.com/laravel/scout/blob/5b5fc4f7a38c879d68e0fd31294672f61bd4c26f/src/Searchable.php#L357-L360) generated by Scout into Typesense. 

So you'd want to add a field called `__soft_deleted` to the Typesense Collection schema to handle soft deletes (see comment below):

```php

...

'typesense' => [
       ...
        'model-settings' => [
            User::class => [
                'collection-schema' => [
                    'fields' => [
                        [
                            'name' => 'name',
                            'type' => 'string',
                        ],
                        [
                            'name' => 'created_at',
                            'type' => 'int64',
                        ],
                        [ /****** Add this field for soft deletes ********************************/
                            'name' => '__soft_deleted', 
                            'type' => 'int32',
                            'optional' => true
                        ],
                    ],
                    'default_sorting_field' => 'created_at',
                ],
                'search-parameters' => [ 
                    'query_by' => 'name, title' 
                ],
            ],
        ],
    ],

```

I'll update the docs in the description with this information shortly.

> Furthermore, if I'm using Typesense how can I delete all my collections for a fresh start?

If you're running on dev, to get a clean slate, you'd want to stop the Typesense server, delete the contents of the `--data-dir` which you specified when starting the process, and then start the process again. 

In a production environment, you'd want to call `DELETE /collections/<name>` on each collection to drop each collection. [Docs](https://typesense.org/docs/0.25.1/api/collections.html#drop-a-collection)

2023-12-15 15:49 UTC, taylorotwell commented
@jasonbosco another bug related to soft delete.

If I do this: 

```php
return User::search('Delpha')->withTrashed()->get();
```

I get a result (as expected because Delpha is trashed).

But if I do this:

```php
return User::search('Delpha')->onlyTrashed()->get();
```

I don't get any results. I would expect to still get my result.

2023-12-23 15:34 UTC, taylorotwell commented
@jasonbosco drafting this again pending response on above.

2024-01-05 22:00 UTC, jasonbosco commented
@taylorotwell - could you give it a shot now? 

@karakhanyans has fixed the issue and also written a test for it.

2024-01-07 17:05 UTC, taylorotwell commented
@jasonbosco @karakhanyans 

OK - thanks. Another question. Let's imagine I have a schema for my user model. I later add another column to the database and want to add it to my schema. I update my Scout configuration file's Typesense schema configuration... then what? I assume the schema isn't automatically updated in Typesense? What is the user story here?

2024-01-08 15:54 UTC, jasonbosco commented
@taylorotwell 

> I update my Scout configuration file's Typesense schema configuration... then what? I assume the schema isn't automatically updated in Typesense?

That's correct. Schema changes need to be done in Typesense directly using the [alter schema endpoints](https://typesense.org/docs/0.25.2/api/collections.html#update-or-alter-a-collection).

Alternatively, there's also an [auto-schema detection](https://typesense.org/docs/0.25.2/api/collections.html#with-auto-schema-detection) mode in Typesense, where users can define field names using regex in the collection schema, so at least new field additions matching a pattern do not need schema alterations, but will be auto-added by Typesense when a document is indexed with that field name pattern. 

We can probably add a note to the configuration section in Scout saying that the schema defined here is only used when the collection is created the first time to make this clear?

2024-01-08 19:01 UTC, taylorotwell commented
@jasonbosco would it be reasonable to make the default config in Scout reflect auto-schema detection?

2024-01-08 20:13 UTC, jasonbosco commented
> would it be reasonable to make the default config in Scout reflect auto-schema detection?

@taylorotwell Setting that to the default could potentially lead to unnecessary fields being indexed and taking up RAM, without the user realizing. For eg, I've commonly seen URL fields getting indexed accidentally, when typically they are only used for display purposes and not for full-text search purposes. 

May be we can call out auto-schema detection as a commented-out field in the schema, with a link to the docs, so users are aware of its existence?

2024-01-09 01:16 UTC, taylorotwell commented
@jasonbosco is there any kind of admin dashboard or something where users can make schema changes? It just feels cumbersome to have to manually craft HTTP calls to update the schema.

2024-01-09 01:27 UTC, jasonbosco commented
@taylorotwell 

The dashboard that the core Typesense team maintains is available as part of Typesense Cloud. 

There's a Postman collection available [here](https://www.postman.com/typesense/workspace/typesense-api/overview).

There's a community-maintained dashboard [here](https://github.com/bfritscher/typesense-dashboard), but it looks like it doesn't support the alter schema endpoint yet.

2024-01-09 15:42 UTC, merged

2024-01-09 15:42 UTC, taylorotwell commented
Thanks 👍